#+TITLE: 2012 年 3 月
#+DATE: 2012-03-01


* 《最炫杜甫风》（转） <2012-03-27 一>
最近杜甫真火啊！

#+BEGIN_EXAMPLE
开元的盛世是我的爱，幽幽的蓬门今始为君开。
什么样的美酒更呀更开怀，什么样的茅屋最耐大风拆。
萧萧的落木从天上来，锦官城姹紫嫣红一夜花成海。
火辣辣的泰山是我们的期待，一路若喜若狂妻子愁何在，我们要愁就要愁的更悠
哉。
你是我身边最美的李白，天子呼唤也不上船来。
悠悠的唱着最炫的杜甫风，让诗记录大唐的兴衰。
我是你课本最美的男孩，我千变万化就是让你猜，悠悠的唱着最炫的杜甫风，是
语文课本最美的姿态。
#+END_EXAMPLE

* 今年你存了什么？CSDN 某人的机智回答 <2012-03-26 一>
问：今年 28 了，你存款多少了？ - 挨踢职涯 / 职场话题

答：存了个老婆。

* 想买个显示器，在 NG 硬件区学了几个指标 <2012-03-24 六>
几个指标：光强，表面油腻感，亮度，bit 抖动，色彩还原

原文：[[http://bbs.ngacn.cc/read.php?tid%3D5013603&amp%3B_fp%3D1][{硬件区满满都是爱爱爱~} 帮忙推荐下 1500 以下 22 寸 16:10 比较护眼的显
示器]]

* 1929~2008 的中国人口统计，我们这代人的压力略大 <2012-03-24 六>
通过下面的数据得出的简单结论：
- 86~90 这几年是人口出生高峰年
- 91 年起，人口出生稳步下降
- 我们这代人的人均资源真少，无论是升学还是工作

#+BEGIN_EXAMPLE
...
1994    16,470,140
1993    17,914,756
1992    18,752,106
1991    20,082,026
1990    26,210,044
1989    25,137,678
1988    24,576,191
1987    25,282,644
1986    23,190,076
1985    20,429,326
...
#+END_EXAMPLE

* 苦学数理化，货与资本家 <2012-03-24 六>
在旧社会里，人们常说：学得文武艺，货与帝王家。

* 集体智慧的典型案例：美味书签 <2012-03-22 四>
特点：
- 云端同步，无论何地，无论什么终端，只要联网，就能访问全部数据；
- 形成自己的网页库，作为高精度的个人定制版搜索引擎；
- 个人知识管理；
- 展示个人的舞台；
  
原文：[[http://www.williamlong.info/archives/3033.html][del.icio.us（美味书签）使用指南]]

* 全民单反全民摄影的年代 <2012-03-14 三>
看来我也要弄个单反了，码农最喜欢了！
#+BEGIN_EXAMPLE
夏小琰 Shar，一个不成熟的半吊子摄影师
18 票，来自 谢金栋、TNT、kang 更多
1.随着科技的发展，单反已经走下神坛，价格更能为公众所接受，且各大相机生产商也已经注意到了入门低端市场，在不断完善产品线。
2.就像玩车玩表一样，很多人玩相机玩的是操控性，单反的操控性还是比 DC 好一些的（当然比不上 Sinar 之类的操控，太精密了）
3.不得不说随着科技的发展，还是有很多人对影像品质要求越来越高，而选择一款入门单反的，因为单反对大多数人而言，可能就是摄影和专业的代名词了。
4.拍摄需要，比如学建筑学的，有时候拍建筑需要移轴镜头或者皮腔相机，相对于大画幅之类的专业相机，单反显然更容易上手，且价格、重量都更容易令人接受。
5.跟风心理，周围人都有，我也想要——你不得不承认持这种想法的人很多。
6.装 B 心理，我相信你身边也有经常扛着单反出门却永远打在 Auto 档的人，这类人给我的感觉就和穿着高跟鞋去爬山的人一样。

我只说了几种我认为比较普遍的情况，欢迎吐槽，哈哈。
其 实现在不是玩单反的人越来越多，而是喜欢摄影的人越来越多，随着传播方式多样化和日常生活的丰富，人们的记录需求、审美需求、情感需求都日益增加，“停下 时光 静止衰老”是很多人的白日梦，如果能在相机里实现，也是一种美好吧。实际上这种需求自 1839 年摄影术被发明之后就从未减少过，不信问问周围父辈的人，他 们年轻的时候大多也把玩过或梦想过一台胶片单反呢，在而今科技更发达，成本更低廉的时代，这种现象也不足为奇了。

最后借机感慨下吧，老实说，全民单反全民摄影的年代，作为一个摄影专业的“半吊子人士“，我的压力着实不小，哈哈。

2011-06-16•2 条评论感谢分享收藏没有帮助•
#+END_EXAMPLE

* 人人网上看到《春》两会版 <2012-03-11 日> 
真有才！
#+BEGIN_EXAMPLE
盼望着，盼望着，两会来了，委员们的脚步近了。
一切都象刚睡醒的样子，欣欣然张开了眼。委员们的身板朗润起来了，肚子涨起来了，脸也红起来了。
代表们偷偷地从包厢里钻出来，从政的，经商的。电视里，网络里，瞧去，一大片一大片满是的。推着，嚷着，开会打几个盹，鼓几次掌，举一举手，和记者捉几回迷藏。步子轻悄悄的，北京饭店的床软绵绵的。
政协的、人大的、无党派，你不让我，我……
……
……
#+END_EXAMPLE

* 人脑分为旧脑，中脑和新脑 <2012-03-08 四>
- 旧脑：生存和繁衍
- 中脑：情绪产生和控制
- 新脑：分析和推理

原文：[[http://www.alibuybuy.com/posts/71171.html][你所没有意识的你自己——浅谈下意识设计]]

* 相濡以沫，不如相忘于江湖 <2012-03-07 三> 
这句话的原义让我惊讶，这么多年来我一直误解了。

* 偏见源于无知或愚昧 <2012-03-06 二>  
- 盲目接收道听途说
- 偏见经常意味着独立思考能力的丧失
- 狭隘，未开化，少见多怪
  
例如：
1. 我一直以来对国内的一些歌曲存在偏见，但现在我逐渐觉得它们听起来也不错
   （《香水有毒》除外，这首歌不能忍）
2. 小时候我对芹菜存在偏见，直到后来我喜欢上了吃芹菜
3. 专家们对网游和电子竞技存在偏见
4. Beyond 吧的吧友对周杰伦存在偏见

* "营销" in CnBeta 评论 <2012-03-05 一>
#+BEGIN_EXAMPLE
第 1 楼 匿名人士 发表于 2012-03-05 22:28:41 
淘宝首页那个七格格店铺里那个笑的很甜的 Model 到底 TMD 是谁啊，害我用了 40 多卷纸了..........
回复 支持(0) 反对(5) 举报
#+END_EXAMPLE

* 代码一入深似海，从此文艺是路人 <2012-03-03 六>
RTRTRT，百度实习第 17 天有感。

* 魔兽战士有三种姿态，战斗，防御，狂暴 <2012-03-03 六>
人类的青年也有三种姿态，普通姿态，文艺姿态，二逼姿态。
