#+TITLE: 2012 年 1 月
#+DATE: 2012-01-01

* 手机与 PC 终究还是大不一样的 <2012-01-29 日>  
将 B/S 比作用户与网站/网络服务间的直通车，这是我听过的对于 B/S 和 C/S 的最独
到的见解。但是这不适合于移动互联网，手机上的网站有 APP 化的趋势。因为在手机
上，屏幕较小，用浏览器作为统一的解决方案完全不妥，针对每个网站的特性设计出
各不相同的 APP 则能提供更好的体验。比如说我在使用了天涯 BBS 的 APP "掌上天
涯" 后，再也不想用 UC 访问天涯了。

* 想要有所成就，必须自律，特别是要减少在网上无意义消耗的时间 <2012-01-28 六>  
恩，说的就是我。最近泡在知乎上的时间太多了！  

* 数码相机的发明者——柯达，破产了 <2012-01-25 三>  
纪念一下。

* 保持简单----纪念 Dennis Ritchie（转） <2012-01-21 六>  
原文：http://www.ruanyifeng.com/blog/2011/10/dennis_ritchie.html

评论：Unix 在 1969 年就可以运行的。

* Ultrabook 超级本的年代 <2012-01-21 六> 
1. SSD 将成为主流，这意味着人们 AFK 时更加倾向于卡掉屏幕而不是关机，这对于
   QQ，360 安全桌面等依赖于开机启动的软件是个挑战。
2. 本届 CES 上，联想的 YOGA 让人耳目一新，大大模糊了超级本与平板间的界限 。
   它使超 级本伪装出平板的体验，也为平板的输入问题提供了解决方案。还为微软和
   Intel 切 入移动互联网提供了一个角度。

* 今天赶火车回家，西安交通特别紧张，差点没赶上 <2012-01-15 日> 
今天没有叫到出租车，6 点 07 上了 205 而火车是 7 点的。6 点 39 赶到火车站，6
点 50 多才挤到车厢里面。7 点 06 火车开动，都不带晚点的。

多亏张建设帮我拎行李，还告诉我当时间紧急时，验票时可以请求插队。我的社会经
验还是浅薄啊！

* 河北话：没图你说个渣渣,气死偶咧 <2012-01-13 五>
我到河北省来……

* 寒假前准备去西安大雁塔逛一圈 <2012-01-13 五>
#+BEGIN_EXAMPLE
大雁塔旅游攻略_百度旅游 

特色活动
1、音乐喷泉表演时间：周一至周五每天 12：00、20：00。周六、周日每天 12：00、
14：00、16：00、18：00、21：00。冬季（11 月到次年 1 月）一般没有表演，春节
时例外。
2、晚间看喷泉表演时人通常都会非常多，特别是夏季的夜晚，最佳观景地点要提前占
位；同时要小心人多拥挤，注意保管好自己的财物。
3、出于安全，最好不要进入喷泉广场的喷水区，尤其是在喷水时切莫走入其中。观看
喷泉时，因为水量大、喷水高，注意保护相机等电子产品，以免被水雾打湿。

时间 场次 喷泉播放时间 周一 2 12:00 21:00/冬季 20:30 周二 1 21:00/冬季
20:30 周三 2 12:00 21:00/冬季 20:30 周四 2 12:00 21:00/冬季 20:30 周五 2
12:00 21:00/冬季 20:30
#+END_EXAMPLE

* 最牛电商：中国铁路订票网（转） <2012-01-11 三>
#+BEGIN_EXAMPLE
网友调侃："它界面丑陋，它 UI 粗糙，它服务器不稳定，它用户 体验更是烂到极点。
但它却是史上最牛电商！未做一分钱的广告，短短数日全球 Alexa 排名暴增，日订单
量有望第一、不愁销售额、转化率当之无愧的第一。它就是———中国铁路订票网。"
#+END_EXAMPLE

* 火电，风电，水电，核电对于听音器材的影响（转） <2012-01-09 一>
这篇文章真是让我大开眼界啊，等我有了钱，一点要买最好的器材，接最好的电来听
音乐！

#+BEGIN_EXAMPLE
bomberfish (538140)
级别: 警告等级 1 威望: -2 发帖: 2119 财富: 428
2012-01-09 15 : 12

1)窃以为，用火电的力度大点，声音偏暖，用水电的声底偏冷，但解析力很高，水电
中，以葛州坝的电音色最好，火电中以北仑电厂的电音质最好，因为烧的无烟煤的比
例最高

2)同一套器材，晚上 8 点到 10 点的时候音色就感觉有点偏冷，晚上 11 点之后声音
明显偏暖，后来才发现高峰电用的是外省的水电，低谷电以本地火电为主，铁证如山！

3)风力发的电层次感很差，听感朦胧，听柴可夫斯基的 D 大调小提琴协奏曲，音场明
显收缩，小提琴部都混在一起

4)风力发电的单机功率在 500w 以下的音色都偏薄，电是三相和两相和音色关系不大，
关键是平衡感，三相电播放大编制的交响乐阵脚明显比两相的要稳！核电适合播放
《终结者》之类的大片伴音。但遗憾水、火、风、核电都并在了国家电网上了，所以
放什么声音都是混论一片。为此我从上海搬家到广州，声音好很多，因为南方电网以
大亚湾核电和两广水电为主，音响既有力度，又比较清澈。

最近准备投资建设独立不并网的雅鲁藏布江水电站，高山雪原的天水，将使音响脱胎
换骨。但可研报告遭到印度的反对。太阳能发电，有何不同？声音偏向温暖,不冷,但
是有点薄。

有个自诩为国内最资深的耳机发烧友，一日试听森海塞尔 HD 650 耳机，听着听着突
然摘下耳机说“今天没法听了，一定是水电站的水位又涨了”，令在场其他烧友目瞪
口呆！(我想这位老兄一定连电力并网输电的基本原理都不懂，但他居然能通过电源线
听出几千里外水电站的水位变化！) 

NGACN 秋风之菠资深水管工
#+END_EXAMPLE

原文：http://bbs.ngacn.cc/read.php?tid=4849557&_fp=1

* 真好玩 <2012-01-08 日>
哈哈哈哈哈哈我们今天出去玩了

2012 年 1 月 8 日 编辑冲突：

哈哈哈哈哈哈我们今天出去玩了，然后吃饱了呵呵！！

* 开始使用 Evernote <2012-01-07 六>
感谢林茜茜同学！通过她的推荐，我开始使用 Evernote。
#+BEGIN_EXAMPLE
林茜茜 ，最好的时候。
9 票，来自 仲毅、brantlin、周韵煊、托娅 更多
我来说一说互联网领域，做产品的个人知识管理方法吧

产品人需要有眼界、有国际视野、有创意、熟悉新兴的产品和模式，我认为这些建立
在一定的积累之上。我使用 Google Reader 和 Evernote 来做个人的知识管理，它们
都能很方便的搜索和查找。
 
Google Reader 用来输入，但努力不被大量信息淹没，而是从中选择能带来启发的信
息来阅读。Evernote 用来记录和输出，看的多了，就有感觉了，会有一些灵感。我会
在 Evernote 里面按照主题来记录，这样也能看到对于一个主题，自己的想法经历了
怎样的发展。

坚持了半年多，受益匪浅。工具不重要，重要的是你。
#+END_EXAMPLE

