#+TITLE: 2012 清明回西安
#+DATE: 2012-04-01

* 第零天
上午去上地站附近的华联超市的稻香村买了很多糕点，下午准备包裹回西安，出了小
区门，在附近的火车票代售点取票，售票员说可能赶不上火车了，我特别着急。

然后我坐地铁，到了西直门后，我打车去北京西站，最后我成功赶上火车了！

* 第一天
和阿飞，张宏，小流氓去逛东大街。去了爬过体验店，然后到真维斯，森马，美特斯
邦威，以纯，MeMighty 等吊丝专属专卖店逛了下，买了二件衬衫一件牛仔裤，然后转
到对面街，去骡马市，阿迪折扣店看了下，又折回原点，吃了香辣鱿鱼。然后准备坐
车回去，期间小流氓失踪了，张宏拉屎了，我和阿飞在等人时顺便吃了烤面筋和西瓜。
最后回到了宿舍。

* 第二天
睡觉睡到了 12 点，然后和傻根到调剂去吃了砂锅粉带。下午到图书馆和阿飞一起自
习，阿飞为 考研复试备考，我学习 Protobuf。4 点半时，和阿飞去球场看傻根打球，
我拍了 N 久，但傻根一球未进。

* 第三天
和傻根，张宏去调剂吃饭，我吃了砂锅土豆粉。回来后，和小流氓，傻根一起去上毕
设课。

* 第四天
与傻根，张宏，流氓四人去爬翠华山。早上四人去吃油条油饼油糕，喝豆浆喝胡辣汤，
然后到公交五公司坐 106 到丈八东路转 923 到黄岱湾，遇到了个西翻的女生，和她
一起坐三轮到了西翻。然后花 15 快做面的到山底售票处，学生门票打 6.5 折，花了
我 180。然后进山了，在山脚下我们吃了凉皮，锅盔和稀饭，4 人花了 21，感觉很便
宜。然后开始爬山，不一会到了天池，我绕着天池岸边一圈，准备到滑雪场看看，走
着走着发现路被封了。所以我们原路折回，看到地图发现到滑雪场 41KM，滑雪场到临
绝顶也是 40 多 KM，坑爹感顿生。于是我们游玩了天池旁边的景点，比如说夏之春，
剑石，悠悠洞，夫妻对拜，风洞，冰洞等等。然后，开始爬山，遇到一条非常长的石
阶。临近山顶有个寺庙，庙门口插着锦旗。然后遇到悬空的铁索桥，还有很陡的铁阶
梯，最后我们到了山顶。拍了几张照后，我们下山了，下山路上我看手机上的照片才
领悟，刚才我们登的山峰就是翠华峰啊！

* 第五天
睡觉睡到了 12 点，然后一直没吃饭。晚上请大家去小寨的韩都里吃自助烤肉。

* 第六天
上午去回民街置办西安的特产待会给百度的同事们尝尝。下午去车站，回北京，有栗
涛陪我一起做火车。是坐票，邻座的几个哥们一个是跳街舞的，一个拿 手机看金庸的
武侠小说。路上我看完了张爱玲的小说《倾城之恋》，女主角叫白流苏，小说开始时，
她的情况很窘迫，小说结束时，她获得了可靠的经济支柱。

* 第七天 <2012-04-09 一>
到站北京。在长椿街旁和栗涛吃了鸡蛋灌饼，然后做地铁会住处，洗了澡到公司，已
经快 12 点了。拎了一堆西安特产，貌似大家不大感兴趣。

* TODO
- 补照片
- 补感想
