#+TITLE: 2012 年 4 月
#+DATE: 2012-04-01

* NEX-5N 不玩儿转接有点儿冤- EVIL 论坛 - 色影无忌 <2012-04-30 一>     
#+BEGIN_EXAMPLE
一言
资深泡菜
泡网分: 84.318
主题: 116
精华: 4
帖子: 10154
注册: 2003 年 11 月

在奶系之前，器材的通用性很差，玩起来不方便。壁垒有两个，一个是卡口，一个是
单反和旁轴法兰距的差异（很多转接无限远不合焦），奶系的作用是打通了镜头的通
用性，所以奶系自己的镜头提不提高不很重要，买它的人多数也是玩转接的。除了莱
卡蔡司，其他厂家的镜头特别是广角的边角成像较差，APS-C 刚好部分的回避了这个
问题，随着新一批数码背景下的全幅镜头的普及，潜在的市场正在逐步成熟，到那时
再出全幅的，从道义到市场，都是水到渠成。
#+END_EXAMPLE

* 在酷我上听到《牧羊曲》 <2012-04-28 六>    
在酷我上听到《牧羊曲》，让我想起大四寒假回家前去大雁塔音乐广场的场景，仿佛
回到了过去。我的 MX 录了视频，有空整理一下。

* 保持饥饿，保持愚蠢，保持初心 <2012-04-23 一>    
凌晨在读《禅者的初心》，听说乔布斯也喜欢这本书。

* 多年之后，人来看我们这个时代 <2012-04-22 日>    
一定会很有意思。

如果遇到了丁磊和李彦宏，可以向他们问下他们创业时的环境跟现在比。

* Path 私密社交 <2012-04-21 六>    
詹强推荐给我的，能记录自己的足迹，看起来我应该会喜欢的。

* 追忆亡灵法师三季稻（转） <2012-04-20 五>   
#+BEGIN_QUOTE
当年的风云人物三季稻三哥，如今可有人还记得？

古诗有云：一法师,顶二字公会,自号三季稻,于荆棘谷四处劫杀.新人闻名即五脏欲裂,
见影则六神不安,碰面竟七窍流血.致使联盟八方震怒,戮力围剿,然其虽九死仍遁出于
十面埋伏.遂流芳百世,名垂千秋,受万人景仰. 万追兵,携千把利刃,皆为百人斩,在东
大陆十地追剿.稻哥通晓便九转乾坤,遁影在八荒之外,遭伏使七步之才.此令部落六族
敬仰,拔刀相助,似他有五命能令小号四脚朝天.已潇洒三年,纵横二世,成一代传奇.

你可以不知道三个代表，但不可以不知道三季稻！！！
#+END_QUOTE

* 为何纳粹的军服被很多人喜欢？ - 知乎 <2012-04-16 一>  
#+BEGIN_EXAMPLE
王博涵
我不是学服装设计的，只是抛砖引玉。
1，重视制服，是法西斯政权的一个重要标志。因为法西斯的独裁政权，希望把个人淹没在集体的浪潮中，而淡化个人意识，增强集体意识的一个重要手段就是统一着装（比如军队）。于是纳粹费尽心机，努力的改进制服，以引导大众的审美。2，普鲁士的传统使然。与英法等国不太一样，普鲁士的军国主义传统使得他们极度重视军队的整齐划一、一丝不苟，加之德国人普遍的比较严谨，所以看起来始终是一副比较完美的形象。
3，名师操刀设计。Hugo Boss 就是在加入纳粹党之后给冲锋队、党卫军等设计制服的人，这么一个日后非常出名的时尚品牌来给他们设计，肯定不会差到哪儿去。
4，精心剪裁。大量的采用收腰、修身的设计，加上日耳曼人相对比较高大，一上身效果自然出来了。相比之下，那个时代的制服大部分还是“直桶”设计。
5，纳粹脑残粉丝太多。无数人崇拜希特勒，玩个二战类的网络游戏，要跟毛子比赛，参赛队伍选拔的时候前 15 名居然有 8 个名字里要不然“党卫军”要不然“希特勒”啥的，真想不明白为啥隔着千山万水，中国居然还会有这么多的纳粹脑残粉。
编辑于 2012-04-16  24 条评论
#+END_EXAMPLE
  
原文：http://www.zhihu.com/question/20180016

* 问什么说 "关于文无第一武无第二"？ <2012-04-11 三>  
按照我的观点，是因为 "文" 的受众广泛，这个市场更加辽阔，所以有了细分市场。
很多从业者在自己的细分市场里找寻到了自己的粉丝。

* 在回北京的火车上大致读玩了 ≪君主论≫ <2012-04-09 一> 
全书共 26 章。第一部分讲了君主国家的种类和获取。据说这本书连国家领导人也喜
爱，我看了一遍，确实挺有意思的，真诚，不虚伪。

* 去回民街买西安特产 <2012-04-06 五>
绿豆糕，皮影戏，黄桂稠酒，水晶糖等等。

* 天涯创办者：邢明 <2012-04-06 五>
#+BEGIN_QUOTE
直面现实的理想主义者 - 天涯总裁邢明　　

邢明是 1991 年毕业的中文系大学生，他说那个时代是充满着理想主义与浪漫色彩的
年代，与时代相符，那时的大学生更是有着“天下兴亡，匹夫有责”的精神。那一代
人无论世事如何变化，身上始终或多或少都有点理想主义、理论先行， “我们在大学
里流行的是看康德和李泽厚。”
#+END_QUOTE

* 徕卡那个 M9 为啥比魅族的 M9 贵那么多？ <2012-04-06 五>
逛京东时，看到某用户的评论。京东评论区奇葩用户很多，奇葩客服也很多。。
#+BEGIN_EXAMPLE
调戏客服专用
等级：铜牌会员
地区：北京
注册日期：2008-06-26
[讨论贴] 这个怎么比魅族的贵那么多。。。。
一样的 m9，魅族的才 2000 多，这个好几万，难道这个能刷安卓 4.0？

看参数感觉这个除了拍照好点，其他都不如 m9，屏幕也不是视网膜的
#+END_EXAMPLE

* 多年之后，爱上凤凰传奇 <2012-04-02 一> 
玲花的声音很让我着迷，这感觉就像我当年痴迷于 Nightwish 的主唱塔佳的声音的感觉
一样。两者都被世人称为 ~金属~ ，只不过前者被戏谑性地称为 ~畜牧业重金属~ 。

想起 09 年左右的时候，我经常和大学室友拿呦呦切克闹开看玩笑，那时的我真是太年
轻，太缺内涵，感受不了这种艺术。

- 最炫民族风：重新认识了凤凰传奇
- 我从草原来：第二首
- 我和草原有个约定：唱腔值得关注
- 香奢夫人：朗朗上口，民族风味浓厚

* 最近在天涯旁观甄子丹，赵文卓，舒淇事件的感受 <2012-04-01 日>
我发现，虽然有很多平台能供普通人表达自己的观点，比如说天涯，微博等。但是舆
论仍然容易被人为地操控，而且我相信现在就有人正在操控天涯的舆论。

大众们倾向于接受，虽然一开始会辩证地接受，但是后来就容易被洗脑和灌输。
