#+TITLE: 2012 年 2 月
#+DATE: 2012-02-01

* 我对新浪微博的一些不同看法 <2012-02-28 二>    
昨天上网时，看见有人说，新浪微博的成功是因为在微博上，人与人是平等的，普通
人可以立刻地与名人产生交流。但是我却有一些不同的看法。

#+BEGIN_EXAMPLE
新浪微博的成功，是因为它认识到，人与人是不平等的。
#+END_EXAMPLE

过去其他的许多互联网产品，比如说论坛和游戏，当用户们刚开始使用它们时，用户
都是平等的，跟现实中的地位是无关的。随着时间，有的用户拥有了比其他用户高的
地位，但这是多年混迹而来的资历，而不是从现实生活中嫁接过来的。

在上述的互联网产品中，用户要取得很高的地位，强大的影响力，需要很大的时间成
本。网民们经常不带任何功利心态，只凭着兴趣，在这些产品中耗费时间，获得了地
位和影响力。但当他们有一段时间不使用这个产品，之后又回归时，发现时过境迁，
之前 地位和影响力已经没有了，他们会感叹 "十年 XX 一场空"。

随着互联网的进化，微博这类 SNS 产品出现了，许多人立刻意识到了它的价值。因为
通过实名认证，他们可以轻易地把他在现实生活中的地位给嫁接过来，成为凌驾于普
通用户之上超级用户，进而攫取经济利益或者名声或者其他一些收益。

* 屌丝：一个字头的诞生（转） <2012-02-27 一>    
#+BEGIN_QUOTE
比惨是一种自我保护的方式。它的心理基础是不患寡而患不均的传统社会认识。人们
不仅物质上要追求平均，心理上也是如此，如果不能和人一起富，就希望大家一起穷。
凡人遇到伤心之事，这时候有一个人对他或她说，我比你更惨，这样心理也就平衡了，
也不那么伤心了。而“屌丝”在网络上的自嘲，则亦有比惨之意，而本质则是一种发
泄和寻求心理的慰藉。“屌丝”更似乎是在宣称，反正我就是这么副屌样，再怎么差
都无所谓了。
#+END_QUOTE

原文：http://news.ifeng.com/opinion/special/diaosi/

* 大学时用了几年 360 浏览器，回想起来感觉还是不错的 <2012-02-24 五>    
- 技术强，速度快，能达到世界之窗的速度；
- 集成了网络收藏夹和手势，并且各种设置保存在云端；
- 大打安全牌，一定程度上实现了绑架用户的效果；

* 厂家主导市场方向，市场主导消费者消费取向 - PCHiFi <2012-02-13 一>   
#+BEGIN_EXAMPLE
无聊跟进 发表于 2011-5-23 22:48  只看该作者

说白了这些都是厂家炒作家用级音箱的概念。

就像 40 年前开始炒 HIFI（高保真），20 年前开始炒多媒体；前 2 个概念炒的时间
太长了，技术也没什么发展余地了，现在开始炒家用级监听。说明白了就是厂家主导
市场方向，市场主导消费者消费取向，厂家不炒作新的概念他们怎么把生产成本很低
的东西翻个十几倍卖给你。电子类产品卖的不是东西，卖的是技术和概念的。

[ 本帖最后由 无聊跟进 于 2011-5-23 23:04 编辑 ]
#+END_EXAMPLE
  
原文：http://www.pchifi.cn/forum.php?mod=viewthread&tid=64335

* 论微软产品的定价 <2012-02-13 一>   
当我看到微软将 Windows 操作系统分成家庭普通版、家庭高级版、专业版、旗舰版来
卖时，我意识到这种市场策略有问题。因为，这四种版本对于微软来说，成本几乎一
样，甚至家庭普通版的成本更高（阉割成本），而这四种版本的出售价格却差异悬殊。
相对而言，谷歌的特点是，每个人都可以完全平等地获得它的服务，虽然每个人对于
给谷歌贡献的价值不一样。简单地说，就是微软与互联网的精神不符合，而谷歌更能
代表互联网精神（如去中心化、平民精神、自由、传播、分享、开放、协作等等），
这也许是微软进军互联网领域流年不利的原因之一吧。

微软的这种定价策略是根据消费者消费能力来进行市场细分的，而不是产品差异化。
想必微软认为正常人会买专业版，富二代会买旗舰版，没钱却想用 Windows 的人买家
庭普通版。就如同 Intel 会将高级的 CPU 降频或者屏蔽核心来当做低级 CPU 来卖一
样，这是一个传统的常见的市场策略。

苹果虽然是一家以卖硬件盈利为主的公司，但它的市场策略却很有互联网的特点，即
最低级的 iPhone 拥有完全够用的存储，并搭载完全功能的操作系统，用户可以享受
到完全的服务。

写了这么长的一段文字，还只给自己看，真蛋疼。。

* 云，管，端。Intel 占了云，ARM 占了端 <2012-02-10 日> 
互联网公司的服务器全部用的都是 Intel 的处理器，而用户的手机用的都是 ARM 的
处理器。看来 Intel 也并非完全落寞啊。

* 京东用户对 X220 的评价 <2012-02-09 日>
#+BEGIN_EXAMPLE
以前用过 X61，跟 X61 一样便携 2012-02-05 10:39
优点： 帅气，册露。
不足： 暂时还没发现缺点哦！
使用心得：
以前用过 X61，优点就是跟 X61 一样很便携。外观比较沉着冷静，符合我这样的高端
商务人士。 每当我背着这款电脑，这款电脑和我满满一裤兜的硬币就已经出卖了我，
我富有，尊贵的身份就这样被暴露在大众视野里。

此评价对我 有用(0) 没用(0)
#+END_EXAMPLE
