#+TITLE: 2013 年度回顾
#+DATE: 2014-02-12
#+KEYWORDS: 年度总结

* 前言
关于年度回顾，我 12 年末就准备写的，但是由于某些已经忘却的原因，没写成。今年我必须
的要写了，否则不久后，我回忘记 13 年是如何度过了，以及获得了哪方面的提高。另外，经
过了一段时间的摸索，我找到了一个（目前看来）最完美的编辑环境，这让我能轻易地写出
一大堆不那么没条理的文字。

此外，我还要把 2012 年的年度回顾给补写一下。

* 自动化运维项目
我的模块作为常驻程序部署到了公司的所有机器上了（量级为 10 万），我想我以后都可能
没机会做这种事情了。

参考 *再见程序员疯狂的岁月* 一文。

* 日志传输系统项目
我负责的是这个程序的 Master 模块，这个项目之后，我终于可以说我完整经历过一个大型的
分布式系统了。

* 知识管理和个人博客
年底那几天，我本计划把项目的代码完善下，并补齐单测。但是我没有这么做，我把这几天
的时间用来折腾 RST，Org，GTD，Clang Complete 了。最终，在我春节前后，我悟出了一个基
于 Org 和 Git 构建我的知识管理，时间管理和个人博客的系统。虽然该做的事情没做，来年上
班我的压力肯定会非常的大，但是从长远看来，我不必感到懊悔，我应该庆幸 *我做出的选
择* 。

* 时间管理
11 月份的时候看了一本书，书名是《拖拉一点也无妨》，从里面学到了一个新名词 *结构化
拖延术* 。 *结构化拖延术* 描述的是一种利用遇到难办事情而产生拖延心理来把一些稍微
好办的事情办完的技术。对照了一下，发现我一直以来其实都是这么做的的，我的很多东西
都是在在拖延其他事情的状态下雪的。这本书为我的行为标榜出了理论依据，很好。

但我的压力还是很大。年末，我开始尝试各种 GTD 工具，希望能用过它来减压。据 GTD 理论所
述，GTD 的最大效用是减少人做事时的心理压力。最终，我选择了 Emacs Org-mode。我现在还
处于在 Org 下面实践 GTD 的阶段，疑惑还是不少，但我还是相信 Org 能帮我实现时间管理的。

另外提一句，我认为的时间管理是 *一种将时间掌握在手中的方法* 。

* 外出旅游
** 春天爬凤凰岭
和张宏一起的，见照片收藏。

** 秋天爬泰山
几个团队一起去的，网盘里有很多照片。

** 爬长城
和阿飞等几个大学同学一起爬的。

* 购入设备
这一年，我入手的设备如下：
| 设备                         | 价格 |
|------------------------------+------|
| Korg PA500 编曲键盘           |      |
| 漫步者 E3000 音箱              |      |
| Macbook Pro 13 2013 Retina 版 |      |
| 铁三角 ATH-C770 耳机           |      |
| 魅族 EP30 耳机                 |      |
| Kindle 5 电子阅读器           |      |
| 三星 S19C200NW 19 寸显示器     |      |
| Razer 炼狱蝰蛇               |      |

* 2014 年计划
** 技术学习
我想学的太多太多，根本无法完全列出来。而我的时间是有限的，我只能在过程中把握。

** 工具学习
继续学习 Vim，Emacs，Eclipse 等等等等。对于每件经典的工具的学习，我都会以系统的方法
对待。

** 写作技能
多谢一些非技术的，总结一些写作的方法论。

** 乐器学习
我期望我今年能抽出时间来练练我的 Korg PA500，并有个阶段性的成果。要不是我仍对我学
会弹琴抱有期望，我早在 13 年 5 月就把它卖掉了。


