#+TITLE: 绝命毒师（Breaking Bad） 
#+DATE: 2014-03-21

* 绝命毒师
2014 年 3 约 18 日凌晨六点，终于将《绝命毒师》看完了。
* 印象深刻的场景
** 资本主义国家里可怜的人民教师
** 老白的觉醒
[S1] 老白狠揍了那个不礼貌的青年一顿，从此老白踏上了与命运相抗的不归路。

** 个人品牌 "Heisenberg" 的建立
老白拿着一袋雷酸汞找 Tuco 要钱，

** 一起制毒的岁月

** "Run"
[S3E12] Jesse 找 Gus 的两个下属复仇，两端势力完全不对等。就在动手之前，老白出现了，
开车撞死了其中一个，并用枪结果了另外一人，并对 Jesse 说: "Run"

** 老白与 Gale 的生存竞争
[S3E13] 

** Gus 之死
[S4E13] 利用 Hector 杀死 Gus 后，老白对 Skyler 说: "I won."，心里终于舒了一口气。

** 新墨西哥州的新一代毒枭的上位
Jesse 和 Mike 要退出，老白直接跟黑帮分销商接上头。老白对他们说: "Say my name. Who
killed gus?"， 分销商回答: "Heisenberg..."，老白: "你特么答得太对了！"。

** Mike 之死
冲动之下，老白向 Mkie 开枪，Mike 濒死前在河边静静地看风景。他对老白说: "Let me die
on peace."

** 老白走投无路
老白想要接一家四口出去逃亡，可是 Skyler 一再追问: "Where is Hank?"，并拿刀赶走老白。
之后，老白彻底处于"众叛亲离"的局面。

** 最后的不甘于命运
老白成了全国通缉犯。在"吸尘器"公司的帮助下，老白隐姓埋名，藏匿在被冰雪覆盖的荒山
野岭。老白对"吸尘器"公司的老板说: 我快不行了，没准你哪天过来发现我已经挂了，我这
里有一大桶钱，你会替我转交给我的家人吗？"吸尘器"公司老板说：我说会你信嘛？

于是，老白踏上了复仇之路。

** 真正的老白
[S5E13] Skyler 厌恶地说你又要把套话重复一遍，老白这次的回答跟以前不同: "I do it
for me. I like it. I'm good at it. I was alive."

** 最后一幕
老白用自制遥控机枪杀死了 Jack 一伙，救出了 Jesse，但是自己也受了重伤。临死前，老白找
到了最心爱的制毒实验室，在这里面结束了自己的一生，背景音乐《my baby blue》响起。
*Walt White* 这个名字，从此在观众心里留下了不可磨灭的印记。

* 口头禅
老白: "We need to talk."

小白: "Hey mom, Hey dad."

Jesse: "Yo, man", "Biatch."

Hank: "Hey buddy."

* 影评
+ [[http://movie.douban.com/review/6481148/][再见老白，再见，老白]]
+ [[http://movie.douban.com/review/6505591/][绝命毒师：五大理由铸就伟大]]
+ [[http://movie.douban.com/review/5130753/][国产缉毒大戏《黑冰 2-绝命毒师》！]]
