#+TITLE: 2015 年 4 月
#+DATE: 2015-04-01

* 本月节奏
本月节奏未知。

* 15 年
* 血泪教训：下班后不要在家里干活！ <2015-04-17 五>
无数次血泪教训告诉我，这个点干活根本没效率。我为什么不早睡，明天早点起来在
干活了？明天早上到班上干活效率多高啊！而且专注力 Max。

我今天就是加班到 23 点半到家的，到家后想继续干活，但是一直到 凌晨 2 点 12 分，
我的活仍然没进展。我决定明早 7 点起床继续干活。这时我想：
- 我干嘛不早点睡？比如说 1 点睡觉，明天 7 点起床？
- 我干嘛不早点睡？比如说 1 点睡觉，明天 7 点起床？
- 我干嘛不早点睡？比如说 1 点睡觉，明天 7 点起床？
- ....
  
（注：现在时刻 2015-04-17 02:47:49）

* 惊闻文锋要离开，写给他一些祝福话语 <2015-04-13 一>
#+BEGIN_QUOTE
感谢文锋在带 Logging 团队的两年间对我的悉心指导，文锋的许多工作理念，尤其是
“把事情做到极致”这一条，已经深深地影响了我。临别之际，祝文锋在新的岗位再
创辉煌！

仲毅 于 2015 年 4 月 13 日
#+END_QUOTE

* 15 年 15 周回顾 <2015-04-13 一>
本周工作上主要在搞数据质量，由于我将开发框架从 Flask 换为 Django，边开发边
学习，所以速度不快。周四和周五会议很多，周五我们组还被经理的经理给批斗了。

学习方面，我的 [[http://elvestar.com/][个人网站]] 1.0 基本已经搞完了，后续我不再需要投入大量精力在上
面了。在这件事上，我已经花了海量的时间，还顺带学了各种相关的技术。我对它的
期望值也很高，我希望它能帮我搭建 *个人知识管理* ， *时间管理* ， *写作平台*
等我的多个重要工作流，我期待这次搞完后，我能终身受益（不想再折腾第二次，呵
呵）

我还花了 4 美元买了 BudgetVM 的一个最低配的 VPS，我把我的个人网站从 GitHub
迁移到它上面后，发现速度快多了。我还可以使用这个 VPS 搭建 VPN，还可以搞一些
其他有意思的事情。我决定过两周在这家买一年的 VPS 压压惊。

生活上面，有三点值得一说：
- 经过这段时间的《七分钟锻炼法》，我现在已经可以完成标准姿势的俯卧撑了！继
  续坚持，健身瘦身目标达成指日可待！
- 最近 *我不大爱关注电竞比赛* 了。因为 Dota2 方面我最喜欢的 iG 战队状态不好，
  TS3 还被 HGT 给淘汰了。而 LOL 方面我最喜欢的 OMG 战队的比赛简直不能看，队
  员相互赌气，全是负能量，完全没有当年在 LPL 势不可挡，各种越塔杀人的霸气了。
  电竞比赛关注少了，NGA 和 SG 刷得也少了，倒是为我省了不少时间用来工作和学
  习。
- 《行尸走肉》看完了第三季，剧情发展到这里，感觉行尸已经彻底沦为该剧的配角
  和点缀了，人与人之间的冲突变为了第一位。另外，该剧没有《绝命毒师》精彩，
  以至于我经常是变写代码变看它。
  
写完碎觉！（2015-04-13 02:41:02）

* 今天 Mac 的 Nginx 抽筋了一小时 <2015-04-09 四>
晚上回家，突然 Nginx 不工作了，看了一下 error.log，发现一直
报 ~apple-touch-icon.png~ 找不到的错。我不断地重启 Nginx，重启 Mac，甚至用
brew 重装了 Nginx，发现它还是不工作。最后。。。

最后，它突然又工作了！

尼玛！

-----

补，过了一会，它又抽了。我尝试将端口号改为 8070，然后发现正常了。

尼玛！
