#+TITLE: 2015 年 1 月
#+DATE: 2015-01-01

* 本月预测
本月事情预计较多，栗涛和学军都要搬走，只剩我一个了。

* DAC 开始了，国内队（西恩群鱼）集体被 EG 和秘密碾压 <2015-01-31 六>
NB 队尤其惨，目前排名垫底。而由众退休人员临时组成的 BG 战队反而排名国内第一。
今天下午 NB vs BG，NB 血崩，让人 Mu 瞪口呆，Hao 无办法。

由于斗鱼没有版权，所以我在虎牙 TV 听周宝龙阿川解说 DAC。这几个家伙太逗了，
特别是 LDD 在比较 OB 和 BG 时，挨个比较了 1，2，3，4 号位，最后来了一句："
难道老子连二冰都不如？"，水友纷纷表示："不如！" 。我当时就笑喷了，随后刷了
一把 SG，发现果然 LDD 再次引了一波节奏。

* 今天参加了百度 2015 年会，主题：It's Time! <2015-01-24 六>
今年不是没人都有票，而我抽票没有抽到，还好好心的同事送了我一张。11 点多时，
蹭了室友同事的车去首都体育馆。年会上拍了不少照片和视频，还打开 QQ 视频将现
场直播给家里人看。想必是一场难忘的记忆，不过感觉没有 2013 年那场举办得好。

* 今晚部门年会，很热闹 <2015-01-23 五>
可惜啥奖都没有抽到，同事有三个人抽中了，两个 iPad，一个佳能 70D。

* 选中了智学苑的房子，付了全年的房租 <2015-01-23 五>
房租是每月 1600。 房东姓闫，在北大教书。网上搜索一下，发现他还是一位挺知名
的计算机相关的教授，主页是：http://net.pku.edu.cn/~yhf/

* 昨晚去看了智学苑的租房 <2015-01-20 二>
1600 元，智学苑，次卧（从客厅隔断的），朝西北，空间较大，木质地板，整套房子很
干净，也挺安静的。室友一个单身百度和两对情侣。

* 今天又去爬了香山 <2015-01-17 六>
真是一趟沁人心脾的回血之旅啊！（前段时间工作太累）

PS: 地铁全面涨价，坑爹！
* OMG vs VG <2015-01-17 六>
OMG 胜了两局，都是靠无状态 Carry 的。第二局 OMG 相当逆风，可是 UZI 投了一条小
龙，这是 OMG 的第五条小龙，S5 赛季下第五条小龙的 Buff 是可以让之前的所有小
龙 Buff 翻倍，相当给力。此时 VG 也刚拿下了大龙，双方在大龙处爆发团战，灵药
的皇子在临时之际，控制住了 VG 的沙漠黄帝和凤女，无状态使用大招秒掉了他们，
然后无状态击杀一人。VG 溃败，OMG 5 人顺势推掉了 VG 的基地。
* LPL 2015 春季赛开赛！ <2015-01-16 五>
等了好久，终于可以看 LOL 的比赛了。LOL 的比赛要比 Dota2 少很多，SG 上一个月
的节奏比 LOL 一年的还要多。不过感觉 LOL 的竞技观赏性是要比 Dota2 好的，看
Dota2 的比赛多是看明星选手，多了一些缅怀过去的青春的成分在里面。

* 最终列车 - MUCC <2015-01-03 六>				      :Music:
当年找遍了全互联网，都没找到带完整前奏的《最终列车》，最后我还是在网易云音
乐上找到了！

顺便怀念一下 Seardna 3。

#+BEGIN_HTML
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="http://music.163.com/outchain/player?type=2&id=779844&auto=0&height=66"></iframe>
#+END_HTML
