#+TITLE: 2015 年 3 月
#+DATE: 2015-03-01

* 本月节奏
春节后上班的第一月，也是我正式实践我的新式时间管理术的第一月。
* 15 年 13 周回顾 <2015-03-30 一>
本周事情：
- 工作上 *终于* 搞定了 Log 集群的迁移，好几晚只睡了不到 4 小时
- 看完了整本交规书，在《驾校一点通》上做完了 1073 道科目一真题，周五下午在
  大兴区东方时尚驾校考试通过了科目一，得分 99！
- 重新开始学习 Django，学习 Less，学习前端设计
- 继续整新版 Vim 开发环境，迁移和新写了大量 snippets，并开始使用 Vim 做
  Python Web 开发。
- 设计了一版个人网站的的导航条已经文章页面
- 周末晚上和大雄吃饭，聊了下各自的工作。他已经提出离职腾讯了。

提升点：
- 做了数天的《七分钟锻炼法》，觉得身体有些变化。看样子很快就能做标准的俯卧
  撑了。
- 体会到了搬到智学苑住的好处了。我每天可以更晚回家，周末可以来公司工作和学
  习。 *我的可利用时间更多了* 。
  

存在问题：
- 有两天没有做《七分钟锻炼法》（当时工作太忙，没心思）
  - 早上没完成，晚上补！
- 用来看 Dota2 比赛，刷 SG 和 NGA 的时间略多
  - 看来我得更专注啊
- 做的和学的东西太散乱，想更好地沉淀
  - 看来每周和每月的 Review 得要开搞了。本篇就是我的 2015 第 13 周的回顾

#+CAPTION: Week-agenda (W13):
| File    | Headline               | Time       |         |
|---------+------------------------+------------+---------|
|         | ALL *Total time*       | *2d 21:33* |         |
|---------+------------------------+------------+---------|
| gtd.org | *File time*            | *2d 21:33* |         |
|         | 工作                   | 1d 17:12   |         |
|         | > 会议                 |            |    0:13 |
|         | > 沟通（电话/邮件/IM） |            |    0:42 |
|         | > 运维                 |            |    3:14 |
|         | > Mi 集群迁移          |            | 1d 2:09 |
|         | > Mi UI                |            |    2:02 |
|         | > 平台易用性优化       |            |    0:18 |
|         | > Mi Master            |            |    0:48 |
|         | > Minos 平台 3.0       |            |    7:46 |
|         | 学习                   | 12:11      |         |
|         | > 时间管理术           |            |    0:15 |
|         | > Web Development      |            |    2:59 |
|         | > 前端学习             |            |    2:47 |
|         | > 重整 Vim 环境        |            |    4:08 |
|         | > 个人网站             |            |    2:02 |
|         | 生活                   | 16:10      |         |
|         | > 学车                 |            |   13:01 |
|         | > 外出                 |            |    2:52 |
|         | > 家务                 |            |    0:17 |
 
* 周六和大雄在北航吃饭闲逛 <2015-03-29 日>
他要从腾讯离职了。当年我们四班去腾讯的有三人，其他两个谢万鸿和张舜达之前就
离职了，他是最后一个从腾讯离职的。

* 今日 iG 在 MAS 上战胜帝国夺冠！ <2015-03-22 日>
在 SG 502 之前发了一贴庆祝：[[http://bbs.sgamer.com/thread-12379010-1-1.html][【技巧】歪歪爱抚：带盾上高是中华名族的传统美德]]

附上 iG 的成员列表：
- 1 号位：BurNIng
- 2 号位：430
- 3 号位：Luo
- 4 号位：Chuan
- 5 号位：Faith

* 今天报名了东方时尚驾校 <2015-03-14 六>
报名驾校花了 5800 元，代办暂住证花了 20 元。此外还遇到一个坑爹事，就是上午
花了 25 元拍了 13 张 1 寸照片，结果回公司后丢了，于是我不得不再花 25 元冲洗
了 13 张！

* 今天是我实践我的 "新式时间管理术" 的第一天 <2015-03-02 一>
今天是我实践我的新式时间管理术的第一天，从上午 10 点 50 到班上，除去吃饭闲聊散
步外的实际工作时间是 6 小时 16 分，具体开销如下：
| File    | Headline                   |   Time |      |
|---------+----------------------------+--------+------|
|         | ALL *Total time*           | *7:18* |      |
|---------+----------------------------+--------+------|
| gtd.org | *File time*                | *7:18* |      |
|         | 工作                       |   6:16 |      |
|         | > 会议                     |        | 0:13 |
|         | > 电话                     |        | 0:03 |
|         | > 运维                     |        | 1:46 |
|         | > Mi 集群迁移              |        | 4:11 |
|         | > Mi UI                    |        | 0:03 |
|         | 生活                       |   0:59 |      |
|         | > 上网                     |        | 0:40 |
|         | > DONE 照片整理 2015-02-25 |        | 0:19 |
|         | 理财购物                   |   0:03 |      |
|         | > 手机冲话费               |        | 0:03 |

我甚至记录了某一分钟具体我在做啥。详情如下
#+BEGIN_EXAMPLE
Monday      2 March 2015 W10
  gtd:        11:05-11:10 Clocked:   (0:05) DONE PS 展现日志某机器发布卡住（李文）
  gtd:        11:12-11:15 Clocked:   (0:03) DONE 改值班人
  gtd:        11:15-11:30 Clocked:   (0:15) DONE PS 展现日志某机器发布卡住（李文）
  gtd:        11:30-11:31 Clocked:   (0:01) TODO 设计和任务分解
  gtd:        11:32-11:45 Clocked:   (0:13) DONE 2015-03-02 例会
  gtd:        11:47-12:03 Clocked:   (0:16) TODO 设计和任务分解
  gtd:        12:10-12:19 Clocked:   (0:09) TODO 后端：修改原传输任务
  gtd:        12:19-12:20 Clocked:   (0:01) TODO 后端：修改原传输任务
  gtd:        13:14-13:56 Clocked:   (0:42) TODO 后端：修改原传输任务
  gtd:        14:02-14:11 Clocked:   (0:09) DONE ASP 某机器发布卡住
  gtd:        14:12-14:14 Clocked:   (0:02) DONE 10032237 日志（佳捷）
  gtd:        14:15-14:17 Clocked:   (0:02) DONE ASP 传输误报警
  gtd:        14:18-14:21 Clocked:   (0:03) PS 展现日志咨询接口人
  gtd:        14:24-14:44 Clocked:   (0:20) TODO 后端：并行传输任务生成
  gtd:        14:44-14:48 Clocked:   (0:04) TODO PS 要求获取日志列表（朋涛，jira: 2340）
  gtd:        14:57-15:02 Clocked:   (0:05) TODO 后端：并行传输任务生成
  gtd:        15:21-15:38 Clocked:   (0:17) TODO PS 要求获取日志列表（朋涛，jira: 2340）
  gtd:        15:39-15:51 Clocked:   (0:12) TODO 后端：并行传输任务生成
  gtd:        16:08-16:13 Clocked:   (0:05) TODO PS 要求获取日志列表（朋涛，jira: 2340）
  gtd:        16:13-16:55 Clocked:   (0:42) TODO 后端：并行传输任务生成
  gtd:        17:00-17:03 Clocked:   (0:03) DONE +230
  gtd:        17:25-17:33 Clocked:   (0:08) TODO 设计和任务分解
  gtd:        17:37-17:44 Clocked:   (0:07) TODO PS 要求获取日志列表（朋涛，jira: 2340）
  gtd:        17:44-18:17 Clocked:   (0:33) TODO 设计和任务分解
  gtd:        19:27-19:31 Clocked:   (0:04) TODO UI：提交集群迁移任务
  gtd:        20:00-20:15 Clocked:   (0:15) TODO UI：提交集群迁移任务
  gtd:        20:16-20:25 Clocked:   (0:09) TODO 教韩超搭建 Minos Web 开发环境
  gtd:        20:26-20:29 Clocked:   (0:03) TODO UI：提交集群迁移任务
  gtd:        20:30-20:49 Clocked:   (0:19) TODO 教韩超搭建 Minos Web 开发环境
  gtd:        20:52-21:00 Clocked:   (0:08) TODO 教韩超搭建 Minos Web 开发环境
  gtd:        21:06-21:46 Clocked:   (0:40) TODO UI：提交集群迁移任务
  gtd:        22:52-23:32 Clocked:   (0:40) 了解车险和事故 2015-03-02
  gtd:        23:34-23:38 Clocked:   (0:04) TODO BWS 发布延时
  gtd:        23:42- 0:01 Clocked:   (0:19) DONE 同步到百度网盘 [照片备份__2015-02-25]
#+END_EXAMPLE

这些记录展示的了我今天的真实工作状态， 也为我提供了改进的依据。

* 下载试用了 Adobe Lightroom <2015-03-01 日>
感觉它的照片管理功能要比 iPhoto 强。另外，这几天被 iPhoto 折磨得痛不欲生，
我的照片接近 1.5W 张，iPhoto 经常让我的 Mac 死机，并且开机极慢！





